// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Week04/internal/dao"
	"Week04/internal/server"
	"Week04/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitNewAir(addr string, db *gorm.DB) *server.HttpServer {
	articleDao := dao.NewArticleDao(db)
	articleService := service.NewArticleService(articleDao)
	httpServer := server.NewServer(addr, articleService)
	return httpServer
}
